#!/usr/bin/env bash
#A Bash script that pings an IP address passed as an argument. It accepts a string as an argument and
#displays "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}" if no argument is passed.
#Ping the IP 5 times

if [ "$1" == "" ];
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
