#!/usr/bin/env bash
# This script displays a list of numbers from 1 to 100
# Displays `FizzBuzz` when the number is a multiple of 3 and 5
# Displays `Fizz` when the number is multiple of 3
# Displays `Buzz` when the number is a multiple of 5
# else, displays the number

for ((i=1; i<=100; i++)); do
	if [ "$((i % 15))" -eq 0 ]; then
		echo "FizzBuzz"
	elif [ "$((i % 5))" -eq 0 ]; then
		echo "Buzz"
	elif [ "$((i % 3))" -eq 0 ]; then
		echo "Fizz"
	else
		echo "$i"
	fi
done
